# Use the official Python image as the base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the poetry files to the working directory
COPY poetry.lock pyproject.toml ./

# Install Poetry
RUN pip install poetry

# Install the project dependencies
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi --no-root
RUN pip install streamlit

# Copy the Streamlit application code to the working directory
COPY streamlit_app.py .
COPY src src/
COPY configs configs/
COPY logs logs/

# Expose the port for Streamlit
EXPOSE 8501

# Set the entrypoint to run Streamlit
CMD ["poetry", "run", "streamlit", "run", "streamlit_app.py", "--server.port", "8501"]
